/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsBoolean,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { CreditBureauDetailCreateNestedManyWithoutUserDetailsInput } from "./CreditBureauDetailCreateNestedManyWithoutUserDetailsInput";
import { AddressDetailCreateNestedManyWithoutUserDetailsInput } from "./AddressDetailCreateNestedManyWithoutUserDetailsInput";
import { EmploymentDetailCreateNestedManyWithoutUserDetailsInput } from "./EmploymentDetailCreateNestedManyWithoutUserDetailsInput";
import { UserOnboardingStateWhereUniqueInput } from "../../userOnboardingState/base/UserOnboardingStateWhereUniqueInput";

@InputType()
class UserDetailCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  userId!: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPersonalEmailVerified?: boolean | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  mobileNumber!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userProvidedFirstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userProvidedLastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  aadhaarName?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  aadhaarDob?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  panName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  pan?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  panDob?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  personalEmail?: string | null;

  @ApiProperty({
    required: false,
    type: () => CreditBureauDetailCreateNestedManyWithoutUserDetailsInput,
  })
  @ValidateNested()
  @Type(() => CreditBureauDetailCreateNestedManyWithoutUserDetailsInput)
  @IsOptional()
  @Field(() => CreditBureauDetailCreateNestedManyWithoutUserDetailsInput, {
    nullable: true,
  })
  creditBureauDetails?: CreditBureauDetailCreateNestedManyWithoutUserDetailsInput;

  @ApiProperty({
    required: false,
    type: () => AddressDetailCreateNestedManyWithoutUserDetailsInput,
  })
  @ValidateNested()
  @Type(() => AddressDetailCreateNestedManyWithoutUserDetailsInput)
  @IsOptional()
  @Field(() => AddressDetailCreateNestedManyWithoutUserDetailsInput, {
    nullable: true,
  })
  addressDetails?: AddressDetailCreateNestedManyWithoutUserDetailsInput;

  @ApiProperty({
    required: false,
    type: () => EmploymentDetailCreateNestedManyWithoutUserDetailsInput,
  })
  @ValidateNested()
  @Type(() => EmploymentDetailCreateNestedManyWithoutUserDetailsInput)
  @IsOptional()
  @Field(() => EmploymentDetailCreateNestedManyWithoutUserDetailsInput, {
    nullable: true,
  })
  employmentDetails?: EmploymentDetailCreateNestedManyWithoutUserDetailsInput;

  @ApiProperty({
    required: false,
    type: () => UserOnboardingStateWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserOnboardingStateWhereUniqueInput)
  @IsOptional()
  @Field(() => UserOnboardingStateWhereUniqueInput, {
    nullable: true,
  })
  userOnboardingState?: UserOnboardingStateWhereUniqueInput | null;
}

export { UserDetailCreateInput as UserDetailCreateInput };
