/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HyperVergeKycSuccessService } from "../hyperVergeKycSuccess.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HyperVergeKycSuccessCreateInput } from "./HyperVergeKycSuccessCreateInput";
import { HyperVergeKycSuccessWhereInput } from "./HyperVergeKycSuccessWhereInput";
import { HyperVergeKycSuccessWhereUniqueInput } from "./HyperVergeKycSuccessWhereUniqueInput";
import { HyperVergeKycSuccessFindManyArgs } from "./HyperVergeKycSuccessFindManyArgs";
import { HyperVergeKycSuccessUpdateInput } from "./HyperVergeKycSuccessUpdateInput";
import { HyperVergeKycSuccess } from "./HyperVergeKycSuccess";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HyperVergeKycSuccessControllerBase {
  constructor(
    protected readonly service: HyperVergeKycSuccessService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HyperVergeKycSuccess })
  @nestAccessControl.UseRoles({
    resource: "HyperVergeKycSuccess",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: HyperVergeKycSuccessCreateInput
  ): Promise<HyperVergeKycSuccess> {
    return await this.service.create({
      data: data,
      select: {
        aadhaarNumber: true,
        aadhaarDob: true,
        panNumber: true,
        panDob: true,
        resPayload: true,
        customerId: true,
        id: true,
        createdAt: true,
        updatedAt: true,
        mobileNumber: true,
        reqPayload: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HyperVergeKycSuccess] })
  @ApiNestedQuery(HyperVergeKycSuccessFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HyperVergeKycSuccess",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<HyperVergeKycSuccess[]> {
    const args = plainToClass(HyperVergeKycSuccessFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        aadhaarNumber: true,
        aadhaarDob: true,
        panNumber: true,
        panDob: true,
        resPayload: true,
        customerId: true,
        id: true,
        createdAt: true,
        updatedAt: true,
        mobileNumber: true,
        reqPayload: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HyperVergeKycSuccess })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HyperVergeKycSuccess",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: HyperVergeKycSuccessWhereUniqueInput
  ): Promise<HyperVergeKycSuccess | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        aadhaarNumber: true,
        aadhaarDob: true,
        panNumber: true,
        panDob: true,
        resPayload: true,
        customerId: true,
        id: true,
        createdAt: true,
        updatedAt: true,
        mobileNumber: true,
        reqPayload: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HyperVergeKycSuccess })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HyperVergeKycSuccess",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: HyperVergeKycSuccessWhereUniqueInput,
    @common.Body() data: HyperVergeKycSuccessUpdateInput
  ): Promise<HyperVergeKycSuccess | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          aadhaarNumber: true,
          aadhaarDob: true,
          panNumber: true,
          panDob: true,
          resPayload: true,
          customerId: true,
          id: true,
          createdAt: true,
          updatedAt: true,
          mobileNumber: true,
          reqPayload: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HyperVergeKycSuccess })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HyperVergeKycSuccess",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: HyperVergeKycSuccessWhereUniqueInput
  ): Promise<HyperVergeKycSuccess | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          aadhaarNumber: true,
          aadhaarDob: true,
          panNumber: true,
          panDob: true,
          resPayload: true,
          customerId: true,
          id: true,
          createdAt: true,
          updatedAt: true,
          mobileNumber: true,
          reqPayload: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
