/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExperianCreditBureauService } from "../experianCreditBureau.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExperianCreditBureauCreateInput } from "./ExperianCreditBureauCreateInput";
import { ExperianCreditBureauWhereInput } from "./ExperianCreditBureauWhereInput";
import { ExperianCreditBureauWhereUniqueInput } from "./ExperianCreditBureauWhereUniqueInput";
import { ExperianCreditBureauFindManyArgs } from "./ExperianCreditBureauFindManyArgs";
import { ExperianCreditBureauUpdateInput } from "./ExperianCreditBureauUpdateInput";
import { ExperianCreditBureau } from "./ExperianCreditBureau";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExperianCreditBureauControllerBase {
  constructor(
    protected readonly service: ExperianCreditBureauService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExperianCreditBureau })
  @nestAccessControl.UseRoles({
    resource: "ExperianCreditBureau",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: ExperianCreditBureauCreateInput
  ): Promise<ExperianCreditBureau> {
    return await this.service.create({
      data: data,
      select: {
        httpStatusCode: true,
        errorMessage: true,
        errorCode: true,
        customerId: true,
        address: true,
        reqPayload: true,
        resPayload: true,
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExperianCreditBureau] })
  @ApiNestedQuery(ExperianCreditBureauFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExperianCreditBureau",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<ExperianCreditBureau[]> {
    const args = plainToClass(ExperianCreditBureauFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        httpStatusCode: true,
        errorMessage: true,
        errorCode: true,
        customerId: true,
        address: true,
        reqPayload: true,
        resPayload: true,
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExperianCreditBureau })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExperianCreditBureau",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ExperianCreditBureauWhereUniqueInput
  ): Promise<ExperianCreditBureau | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        httpStatusCode: true,
        errorMessage: true,
        errorCode: true,
        customerId: true,
        address: true,
        reqPayload: true,
        resPayload: true,
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExperianCreditBureau })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExperianCreditBureau",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ExperianCreditBureauWhereUniqueInput,
    @common.Body() data: ExperianCreditBureauUpdateInput
  ): Promise<ExperianCreditBureau | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          httpStatusCode: true,
          errorMessage: true,
          errorCode: true,
          customerId: true,
          address: true,
          reqPayload: true,
          resPayload: true,
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExperianCreditBureau })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExperianCreditBureau",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ExperianCreditBureauWhereUniqueInput
  ): Promise<ExperianCreditBureau | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          httpStatusCode: true,
          errorMessage: true,
          errorCode: true,
          customerId: true,
          address: true,
          reqPayload: true,
          resPayload: true,
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
