/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { KnowlarityMakeCallService } from "../knowlarityMakeCall.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { KnowlarityMakeCallCreateInput } from "./KnowlarityMakeCallCreateInput";
import { KnowlarityMakeCallWhereInput } from "./KnowlarityMakeCallWhereInput";
import { KnowlarityMakeCallWhereUniqueInput } from "./KnowlarityMakeCallWhereUniqueInput";
import { KnowlarityMakeCallFindManyArgs } from "./KnowlarityMakeCallFindManyArgs";
import { KnowlarityMakeCallUpdateInput } from "./KnowlarityMakeCallUpdateInput";
import { KnowlarityMakeCall } from "./KnowlarityMakeCall";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class KnowlarityMakeCallControllerBase {
  constructor(
    protected readonly service: KnowlarityMakeCallService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: KnowlarityMakeCall })
  @nestAccessControl.UseRoles({
    resource: "KnowlarityMakeCall",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: KnowlarityMakeCallCreateInput
  ): Promise<KnowlarityMakeCall> {
    return await this.service.create({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        customerId: true,
        agentId: true,
        customerMobileNumber: true,
        agentMobileNumber: true,
        reqPayload: true,
        resPayload: true,
        httpStatusCode: true,
        errorCode: true,
        errorMessage: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [KnowlarityMakeCall] })
  @ApiNestedQuery(KnowlarityMakeCallFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "KnowlarityMakeCall",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<KnowlarityMakeCall[]> {
    const args = plainToClass(KnowlarityMakeCallFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        customerId: true,
        agentId: true,
        customerMobileNumber: true,
        agentMobileNumber: true,
        reqPayload: true,
        resPayload: true,
        httpStatusCode: true,
        errorCode: true,
        errorMessage: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: KnowlarityMakeCall })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KnowlarityMakeCall",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: KnowlarityMakeCallWhereUniqueInput
  ): Promise<KnowlarityMakeCall | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        customerId: true,
        agentId: true,
        customerMobileNumber: true,
        agentMobileNumber: true,
        reqPayload: true,
        resPayload: true,
        httpStatusCode: true,
        errorCode: true,
        errorMessage: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: KnowlarityMakeCall })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KnowlarityMakeCall",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: KnowlarityMakeCallWhereUniqueInput,
    @common.Body() data: KnowlarityMakeCallUpdateInput
  ): Promise<KnowlarityMakeCall | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          customerId: true,
          agentId: true,
          customerMobileNumber: true,
          agentMobileNumber: true,
          reqPayload: true,
          resPayload: true,
          httpStatusCode: true,
          errorCode: true,
          errorMessage: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: KnowlarityMakeCall })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KnowlarityMakeCall",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: KnowlarityMakeCallWhereUniqueInput
  ): Promise<KnowlarityMakeCall | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          customerId: true,
          agentId: true,
          customerMobileNumber: true,
          agentMobileNumber: true,
          reqPayload: true,
          resPayload: true,
          httpStatusCode: true,
          errorCode: true,
          errorMessage: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
