/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AddressDetailService } from "../addressDetail.service";
import { AddressDetailCreateInput } from "./AddressDetailCreateInput";
import { AddressDetailWhereInput } from "./AddressDetailWhereInput";
import { AddressDetailWhereUniqueInput } from "./AddressDetailWhereUniqueInput";
import { AddressDetailFindManyArgs } from "./AddressDetailFindManyArgs";
import { AddressDetailUpdateInput } from "./AddressDetailUpdateInput";
import { AddressDetail } from "./AddressDetail";

export class AddressDetailControllerBase {
  constructor(protected readonly service: AddressDetailService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AddressDetail })
  async create(
    @common.Body() data: AddressDetailCreateInput
  ): Promise<AddressDetail> {
    return await this.service.create({
      data: {
        ...data,

        userDetail: data.userDetail
          ? {
              connect: data.userDetail,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        inBlacklistedRegion: true,
        state: true,
        country: true,
        latitude: true,
        longitude: true,

        userDetail: {
          select: {
            id: true,
          },
        },

        pincode: true,
        addressType: true,
        city: true,
        addressLine: true,
        inApprovedRegion: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AddressDetail] })
  @ApiNestedQuery(AddressDetailFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<AddressDetail[]> {
    const args = plainToClass(AddressDetailFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        inBlacklistedRegion: true,
        state: true,
        country: true,
        latitude: true,
        longitude: true,

        userDetail: {
          select: {
            id: true,
          },
        },

        pincode: true,
        addressType: true,
        city: true,
        addressLine: true,
        inApprovedRegion: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AddressDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: AddressDetailWhereUniqueInput
  ): Promise<AddressDetail | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        inBlacklistedRegion: true,
        state: true,
        country: true,
        latitude: true,
        longitude: true,

        userDetail: {
          select: {
            id: true,
          },
        },

        pincode: true,
        addressType: true,
        city: true,
        addressLine: true,
        inApprovedRegion: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AddressDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: AddressDetailWhereUniqueInput,
    @common.Body() data: AddressDetailUpdateInput
  ): Promise<AddressDetail | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          userDetail: data.userDetail
            ? {
                connect: data.userDetail,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          inBlacklistedRegion: true,
          state: true,
          country: true,
          latitude: true,
          longitude: true,

          userDetail: {
            select: {
              id: true,
            },
          },

          pincode: true,
          addressType: true,
          city: true,
          addressLine: true,
          inApprovedRegion: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AddressDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: AddressDetailWhereUniqueInput
  ): Promise<AddressDetail | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          inBlacklistedRegion: true,
          state: true,
          country: true,
          latitude: true,
          longitude: true,

          userDetail: {
            select: {
              id: true,
            },
          },

          pincode: true,
          addressType: true,
          city: true,
          addressLine: true,
          inApprovedRegion: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
